### ISSUE TITLE
ERROR: Could not start server, is another program on udp:53?

### ISSUE THREAD

**Issue by Epicloudygamer** [Crypt0s/FakeDns#28]
Hi! I am trying to run the python file over repl.it but I keep getting this error.

"ERROR: Could not start server, is another program on udp:53?"

https://repl.it/@EthanNasrullah/ubdns

**Comment by Crypt0s** [comment]
@Epicloudygamer you must be able to become root in order to utilize any ports from 1024 and below.  As DNS uses port 53, it requires root to run and repl.it does not provide root users on its service.  You will have to run the script using your own server or via another service provider.  I recommend Google Compute since I believe they give you some free credit if you are a first-time user.

**Comment by pdelteil** [comment]
If you are using Linux it's likely you have some service listening on port 53, such as `systemd-resolved`. To run FakeDNS, you will need to stop this service using `sudo systemctl disable --now systemd-resolved.service` 

More [info](https://www.hacking.land/2018/09/singularity-dns-rebinding-attack.html?m=1)
