### ISSUE TITLE
FakeDns CNAME mode - how to config

### ISSUE THREAD

**Issue by cryptomadco** [Crypt0s/FakeDns#30]
Hi !
I want  know, how is it possible to pass CNAME in FakeDNS config file and run FakeDNS with CNAME mode .

Thanks.

**Comment by Crypt0s** [comment]
@cryptomadco thanks for the question.

in the config:
`CNAME [dns_name] [cname_answer]`

I realized I didn't have an example of this in the dns.conf.example configuration file and have since added it.  Please let me know if you have any problems.

Oh, and heads up, I changed the codebase to python3, so be aware of that if you re-clone the code to take a look.
